name: Hugin CLI Main Pipeline

env:
  GITHUB_REGISTRY: 'ghcr.io'
  GITHUB_OWNER: 'kryptokrona'
  GITHUB_DOCKER_IMAGE: 'hugin-cli'
  BUILD_TYPE: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build: ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            name: "Ubuntu Latest GCC / x64",
            artifact: "ubuntu-latest-x64",
            os: ubuntu-22.04,
            cc: "gcc",
            architecture: x64
          }
    steps:
      - uses: actions/checkout@v2

      # Ubuntu 22.04
      - name: Install dependencies
        if: matrix.config.name == 'Ubuntu Latest GCC / x64'
        run: sudo apt-get -y install libssl-dev

      - name: mkdir build
        if: matrix.config.name == 'Ubuntu Latest GCC / x64'
        run: mkdir build

      - name: Build Ubuntu Target
        if: matrix.config.name == 'Ubuntu Latest GCC / x64'
        run: |
          cmake ..
          make
        working-directory: build

      - name: Upload Ubuntu Artifact
        if: matrix.config.name == 'Ubuntu Latest GCC / x64'
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest-x64
          path: |
            build/Hugin
