name: Hugin CLI Pull Request Pipeline

env:
  BUILD_TYPE: Debug

on: [pull_request]

jobs:
  build:
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.architecture }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "Ubuntu Latest GCC",
              os: ubuntu-22.04,
              cc: "g++",
              architecture: x64,
            }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Ubuntu 22.04
      - name: Install dependencies
        if: matrix.config.name == 'Ubuntu Latest GCC'
        run: sudo apt-get -y install libssl-dev libsqlcipher-dev

      - name: Build Ubuntu Target
        if: matrix.config.name == 'Ubuntu Latest GCC'
        run: make
