name: Hugin CLI Pull Request Pipeline

env:
  BUILD_TYPE: Debug

on: [ pull_request ]

jobs:
  build:
    name: "Build: ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            name: "Ubuntu Latest GCC / x64",
            artifact: "ubuntu-latest-x64",
            os: ubuntu-22.04,
            cc: "gcc",
            architecture: x64
          }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Ubuntu 22.04
      - name: Install dependencies
        if: matrix.config.name == 'Ubuntu Latest GCC / x64'
        run: sudo apt-get -y install libssl-dev

      - name: mkdir build
        if: matrix.config.name == 'Ubuntu Latest GCC / x64'
        run: mkdir build

      - name: Build Ubuntu Target
        if: matrix.config.name == 'Ubuntu Latest GCC / x64'
        run: |
          cmake ..
          make
        working-directory: build